# ruff.toml
line-length = 100
target-version = "py310"

[lint]
# Включаем базовые проверки: стиль, ошибки, апгрейды синтаксиса и сортировку импортов
select = ["E", "F", "I", "UP"]
# При желании можно временно игнорировать E501, но мы уже укоротили строки в тесте
ignore = []

[lint.isort]
# Разделяем стандартную библиотеку и сторонние зависимости, группа пустой строки между ними
combine-as-imports = true
